import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const packageJsonPath = path.join(root, "package.json");
const outputPath = path.join(root, "src", "generated", "version.ts");
const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));

if (typeof packageJson.version !== "string" || packageJson.version.length === 0) {
  throw new Error("package.json version must be a non-empty string");
}

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/generate-version.mjs. Do not edit by hand.\nexport const version = ${JSON.stringify(packageJson.version)};\n`,
  "utf8"
);
